### ISSUE TITLE
Section 4.5 (Name Res. Block) - MAC/EUI address to name mapping?

### ISSUE THREAD

**Issue by eqvinox** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#118]
Hi all,

very simple question: is there any plan/possibility to create a NRB option for MAC/EUI-48 (and for completeness EUI-64) to name mappings?

Presumably it'd just be `'02 ca ff ee f0 0d'"teapot under test"` for the data contents; is it possible to "pre-allocate" two (48/64 bit) record types for this?

**Comment by mcr** [comment]
It sure would be welcome.  At this point, what we really need is more conversation on opsawg@ietf.org to get the documents actually, and clearly adopted.

**Comment by guyharris** [comment]
Added in #119.
