### ISSUE TITLE
Should we avoid a mix of 'time stamp' and  'timestamp'?

### ISSUE THREAD

**Issue by fxlb** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#139]
There are many  'timestamp(s)', a few 'time stamp(s)' with mixed cases.

$ git grep -c -i  'time stamp' *.md
draft-ietf-opsawg-pcap.md:2
draft-ietf-opsawg-pcaplinktype.md:1

$ git grep -c -i  'timestamp' *.md
draft-ietf-opsawg-pcap.md:5
draft-ietf-opsawg-pcapng.md:27
draft-richardson-opsawg-pcapng-extras.md:2

Should we use only [tT]imestamp(s)?

**Comment by henkbirkholz** [comment]
> Should we use only [tT]imestamp(s)?

definitely a +1

**Comment by fxlb** [comment]
In the RFCs, there are 23 times more `timestamp` than `time stamp'.`

**Comment by fxlb** [comment]
If agreed, there is the PR #141.

**Comment by guyharris** [comment]
> In the RFCs, there are 23 times more timestamp than time stamp.

"The RFCs" as in "all RFCs as of some recent date"?

**Comment by guyharris** [comment]
In any case, +1.

Pull request #141 merged.

**Comment by fxlb** [comment]
All RFCs retrieved a few month ago:
```
$ grep -i -r 'timestamp' $(find ../RFC-all -iname '*.txt')|wc -l
12636
$ grep -i -r 'time stamp' $(find ../RFC-all -iname '*.txt')|wc -l
543
```
