### ISSUE TITLE
Should we keep the two texts '32-bit' versus '32 bits'? (and others 16, 64, ... )

### ISSUE THREAD

**Issue by fxlb** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#151]
`git grep -nE '([0-9]-bit|[0-9] bit)' '*.md'` shows them.

**Comment by guyharris** [comment]
"N-bit" is a [compound modifier](https://en.wikipedia.org/wiki/Compound_modifier), and is typically hyphenated; we should consistently do so, and, in 75d36463ead8f58c7e1b02a03c4fab29ed91dec6, I've fixed all the occurrences that I found, along with some occurrences of "N octet".

"N bits" isn't a compound modifier, it's a phrase with a count of bits (and "1 bit" is also not a compound modifier if it doesn't modify something, as in "a 1-bit field").

So "N bit", when used as a modifier, should be hyphenated; "N bits" and "1 bit", when not used as a modifier, shouldn't be.
