### ISSUE TITLE
Sysdig Standardized Block Type Codes

### ISSUE THREAD

**Issue by bubbasnmp** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#165]
Is it correct that the Sysdig block numbers did not increment as hexadecimal numbers?  

```
0x00000209	Sysdig Process Info Block, version 3
0x00000210	Sysdig Process Info Block, version 4
```
Why not:  
```
0x00000209	Sysdig Process Info Block, version 3
0x0000020A	Sysdig Process Info Block, version 4
```

https://www.ietf.org/archive/id/draft-tuexen-opsawg-pcapng-03.html#name-standardized-block-type-cod  
```
0x00000201	Sysdig Machine Info Block
0x00000202	Sysdig Process Info Block, version 1
0x00000203	Sysdig FD List Block
0x00000204	Sysdig Event Block
0x00000205	Sysdig Interface List Block
0x00000206	Sysdig User List Block
0x00000207	Sysdig Process Info Block, version 2
0x00000208	Sysdig Event Block with flags
0x00000209	Sysdig Process Info Block, version 3
0x00000210	Sysdig Process Info Block, version 4
0x00000211	Sysdig Process Info Block, version 5
0x00000212	Sysdig Process Info Block, version 6
0x00000213	Sysdig Process Info Block, version 7
```

**Comment by guyharris** [comment]
@geraldcombs? @ldegio?

**Comment by bubbasnmp** [comment]
I'm still learning my way around. Assuming this is the master source for `libscap`.  
https://github.com/falcosecurity/libs/blob/master/userspace/libscap/scap_savefile.h#L100  
  
`#define PL_BLOCK_TYPE_V4 0x210`

**Comment by guyharris** [comment]
It appears that the code does, in fact, go from 0x209 to 0x0210, in which case the spec should reflect that.

**Comment by bubbasnmp** [comment]
Is this the most current spec: https://datatracker.ietf.org/doc/draft-ietf-opsawg-pcapng/ ?  
It goes up to 0x00000213.   
  
[wiretap/pcapng_module.h](https://gitlab.com/wireshark/wireshark/-/blob/master/wiretap/pcapng_module.h) has entries up to `0x00000222` with another jump from `0x00000219` to `0x00000220`.

**Comment by packetfoo** [comment]
> @geraldcombs? @ldegio?

Not sure how that one happened - back then (in February 2014) Loris asked for block numbers and we agreed on 0x200-0x206 at the time, per email. I didn't find anything regarding higher numbers being added later.

**Comment by packetfoo** [comment]
> > Not sure how that one happened
> 
> "That" as in "Sysdig adding additional block types" or "adding those block types to the specification"?

As in "Sysdig adding additional block types". I added the first block types to the specification in agreement wit Loris, which may not have been an ideal way of proceeding. I didn't know a better way back at the time.
