### ISSUE TITLE
Need to specify the IDB if_tzone option format

### ISSUE THREAD

**Issue by hadrielk** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#24]
Currently the IDB if_tzone option is declared but not specified. (a signed int32 for number of seconds West of UTC?)

I'm not sure why this option is in the IDB instead of the SHB, so that might be something to think about too. (I guess if your system is really, really big, then you could have interfaces in different timezones... ;)

**Comment by hadrielk** [comment]
Ignore the second remark about it being in SHB instead of IDB - keeping it in IDB will make life easier for mergecap. :)

**Comment by guyharris** [comment]
> Ignore the second remark about it being in SHB instead of IDB - keeping it in IDB will make life easier for mergecap.

Exactly - you might merge two captures, on two different interfaces, done in two different time zones.

**Comment by guyharris** [comment]
> I would vote to replace it with if_tzid, which is a string containing a "timezone" id from [the IANA Time Zone Database](https://www.iana.org/time-zones). See [the tzdb Theory file](https://www.ietf.org/timezones/theory.html) for more information; I put "timezone" in quotes because tzdb regions don't necessarily correspond to time zones.

Done in e63374c8aa03fdfd296042ff92c4fc565b2b2980, which adds that string option under the name if_iana_tzname, and deprecate if_tzone, and further edited in f723acfa7785f4de27e366af5dae14f087a8932c, ebbe8cf24c1963d593be8531467a6f24ec0eae66, and c100ba99cf7da09cb2e19236df680b20bf179593.
