### ISSUE TITLE
Question about pcap draft

### ISSUE THREAD

**Issue by fxlb** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#71]
Same URI two times in the generated text and pdf (not in html).
Should be avoided?
```
11.2.  URIs

   [1] http://www.tcpdump.org/linktypes.html

   [2] http://www.tcpdump.org/linktypes.html
```

**Comment by guyharris** [comment]
I didn't see anything obvious in [RFC 7991](https://tools.ietf.org/html/rfc7991) to give an eref a name and to refer indirectly to a named eref; what you've come up with in #73 may be the best that can be done.

**Comment by fxlb** [comment]
Yes, it solves also the problem of missing URIs references in generated HTML.

**Comment by fxlb** [comment]
The generated HTML for pcapng draft has also missing URIs references like pcap one had before xref use.

**Comment by guyharris** [comment]
> The generated HTML for pcapng draft has also missing URIs references like pcap one had before xref use.

As with pcap, so with pcapng; time for another pull request.

**Comment by guyharris** [comment]
So is [the current generated HTML](https://pcapng.github.io/pcapng/draft-tuexen-opsawg-pcapng.html), as produced from extended Markdown, fixed, or does it still have those issues?

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > So is [the current generated
    > HTML](https://pcapng.github.io/pcapng/draft-tuexen-opsawg-pcapng.html),
    > as produced from extended Markdown, fixed, or does it still have those
    > issues?

The markdown generator has now fixed the hangIndent issue, if that's what you
are referring to.
